# Generated by Django 2.0.7 on 2018-12-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181213_2239'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_disease',
            field=models.ManyToManyField(blank=True, to='accounts.Disease'),
        ),
    ]
