# Generated by Django 2.1.3 on 2018-11-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ois_app', '0002_auto_20181119_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='data_of_birth',
            new_name='date_of_birth',
        ),
    ]
