# Generated by Django 2.0.7 on 2018-12-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='uri',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='uri',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
