# Generated by Django 2.0.7 on 2018-12-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_disease_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.DoctorProfile'),
        ),
    ]
