# Generated by Django 2.1.3 on 2018-12-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name_slug', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('uri', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('ame_slug', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('uri', models.CharField(max_length=500)),
            ],
        ),
    ]
