# Generated by Django 2.1.3 on 2018-12-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_disease_symptom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='ame_slug',
            new_name='name_slug',
        ),
    ]
