# Generated by Django 2.1.3 on 2018-12-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181212_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
