# Generated by Django 2.0.7 on 2018-12-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181213_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='symptom',
            name='can_cause_disease',
            field=models.ManyToManyField(to='accounts.Disease'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='can_cause_symptom',
            field=models.ManyToManyField(to='accounts.Symptom'),
        ),
        migrations.AddField(
            model_name='symptom',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='accounts.Symptom'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
