# Generated by Django 2.0.7 on 2018-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20181213_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='can_cause_disease',
            field=models.ManyToManyField(blank=True, to='accounts.Disease'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='can_cause_symptom',
            field=models.ManyToManyField(blank=True, to='accounts.Symptom'),
        ),
    ]
