# Generated by Django 2.0.7 on 2018-12-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20181213_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='accounts.Symptom'),
        ),
    ]
